### ISSUE TITLE
Dynamic Obfuscation

### ISSUE THREAD

**Issue by mgcdanny** [dancromartie/json-obfuscator#1]
Instead of doing a string replace, can the config file specify a function that acts upon the datum to be obfuscated?

for example,  I want to obfuscate date of birth with a new date that maintains whether or not the date 21 years ago but not more than 50 years.  

04/04/90  would be obfuscated to andy date that lead to at least  21 years ago but not more than 50.

**Comment by dancromartie** [comment]
good point.  should be doable with new style... check out the readme
